//Users
export const SET_SELECTED_USER_ID = 'SET_SELECTED_USER_ID';
export const UPDATE_USERS_TABLE = 'UPDATE_USERS_TABLE';
export const CLEAR_SELECTED_USER_ID = 'CLEAR_SELECTED_USER_ID';

//SnackBar
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
